var mongoose = require('mongoose');

var IngredientSchema = new mongoose.Schema({
    name:String,
    image:String,
    energy:Number,
    fat:Number,
    carbohydrate:Number,
    protein:Number,
    water:Number,
    starch:Number,
    fiber:Number,
    sugars:Number,
    glucose:Number,
    fructose:Number,
    maltose:Number,
    oligoSaccharide:Number,
    freeSugar:Number,
    nsp:Number,
    glactose:Number,
    sucrose:Number,
    lactose:Number,
    saturatedFat:Number,
    cisMono:Number,
    omegaThree:Number,
    cisPoly:Number,
    cholestrol:Number,
    monoSaturatedFat:Number,
    polySaturatedFat:Number,
    omegaSix:Number,
    transFattyAcids:Number,
    sodium:Number,
    chloride:Number,
    phosphorus:Number,
    iron:Number,
    copper:Number,
    selenium:Number,
    potassium:Number,
    calcium:Number,
    magnesium:Number,
    zinc:Number,
    manganese:Number,
    iodine:Number,
    vitaminA:Number,
    carotene:Number,
    vitaminE:Number,
    thiaminBOne:Number,
    niacinTotalBThree:Number,
    tryptophan:Number,
    vitaminBSix:Number,
    vitaminBTwelve:Number,
    vitaminC:Number,
    retinol:Number,
    vitaminD:Number,
    vitaminKOne:Number,
    riboflavin:Number,
    niacin:Number,
    pantothenicAcid:Number,
    folicAcid:Number,
    biotin:Number,
    gi:Number,
    pral:Number,
    gl:Number,
    caffeine:Number

})

module.exports = mongoose.model('Ingredient', IngredientSchema);